apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnf-operators-cnfdb2
  namespace: telco-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
operation:
  initiatedBy:
    automated: true
  retry:
    limit: 5
spec:
  project: default
  destination:
    namespace: telco-gitops
    server: https://api.cnfdb2.e2e.bos.redhat.com:6443 
  source:
    directory:
      jsonnet: {}
    path: cnf20.cloud.lab.eng.bos.redhat.com/remote-clusters/cnfdb2/base
    repoURL: https://github.com/alosadagrande/telco-gitops-mgmt.git
    targetRevision: main
  # Sync policy
