---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-mgmt-base
  namespace: telco-gitops
spec:
  # The argocd project the application belongs to
  project: default
  destination:
    namespace: 'telco-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/openshift-telco/telco-gitops-mgmt.git'
    targetRevision: HEAD
    path: mgmt.telco.shift.zone
    directory:
      recurse: false
  # Sync policy
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      # (equivalent to 'kubectl apply --validate=true')
      - Validate=false
      - CreateNamespace=true
    retry:
      # unlimited if less than 0
      limit: -1
      backoff:
        # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        duration: 1m
        # a factor to multiply the base duration after each failed retry
        factor: 2
        # the maximum amount of time allowed for the backoff strategy
        maxDuration: 3m