apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    local.storage.openshift.io/owner-name: local-disks
    local.storage.openshift.io/owner-namespace: openshift-local-storage
  name: lso-filesystemclass
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
