apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    local.storage.openshift.io/owner-name: local-disks
    local.storage.openshift.io/owner-namespace: openshift-local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: lso-filesystemclass
