---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: cluster-eric-prov-wait-job
  # generateName: csv-wait-job-
  namespace: telco-gitops
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "ArgoCD Hook"
              CSV_STATUS="Pausing $SLEEP seconds..."
              PROV_CLUSTER=eric1
              while [[ "$CSV_STATUS" != *"InstallationCompleted"* ]]; do
                echo "Waiting for the $PROV_CLUSTER cluster to be ready. ($CSV_STATUS)"
                sleep $SLEEP
                CSV_STATUS=$( oc get agentclusterinstalls eric1 -n eric1 -o json | python -m json.tool | grep '"reason":'  | sort -u )
              done
              echo "$PROV_CLUSTER provisioning completed! Hooray!"
          imagePullPolicy: IfNotPresent
          name: mcp-wait-job
          env:
          - name: SLEEP
            value: "3"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
