---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: telco-gitops-ztp
  namespace: telco-gitops
spec:
  generators:
  - git:
      repoURL: https://gitlab.cee.redhat.com/sysdeseng/5g-ericsson.git
      revision: HEAD 
      directories:
        - path: demos/ztp-europe-lab-demo/argocd/clusters/*
  template:
    metadata:
      name: '01-ztp-{{path.basename}}'
      namespace: telco-gitops
    spec:
      destination:
        namespace: telco-gitops
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: https://gitlab.cee.redhat.com/sysdeseng/5g-ericsson.git
        targetRevision: HEAD
        path: '{{path}}/ztp'
